FROM ubuntu:24.04

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
    && apt-get install -y git make cppcheck gcc-arm-none-eabi gcc bear

RUN useradd -rm -d /home/build -s /bin/bash -g root -G sudo -u 1001 build

USER build

WORKDIR /home/build
