#ifndef TEST_TYPES_H
#define TEST_TYPES_H

typedef enum {
    // GPIO tests options
    GPIO_TEST_BLINK_LED,
    GPIO_TEST_READ_WRITE,
    GPIO_TEST_IT,
    // USART tests options
    USART_TEST_WRITE,
    USART_TEST_READ,
    USART_TEST_WRITE_IT,
    USART_TEST_READ_IT,
    // I2C test options
    I2C_TEST_MASTER_TRANSMIT,
    I2C_TEST_MASTER_RECEIVE,
    I2C_TEST_SLAVE_TRANSMIT,
    I2C_TEST_SLAVE_RECEIVE,
    I2C_TEST_MASTER_TRANSMIT_IT,
    I2C_TEST_MASTER_RECEIVE_IT,
    I2C_TEST_SLAVE_TRANSMIT_IT,
    I2C_TEST_SLAVE_RECEIVE_IT,
    // Misc tests options
    MISC_TEST_ASSERT,
    MISC_TEST_GET_CLOCK,
    MISC_TEST_PRINTF,
} test_type_e;

#endif
